# CreateNullAtSelection
# Initial code generated by Softimage SDK Wizard
# Executed Thu Feb 4 11:56:42 PST 2010 by andy
# 
# Tip: To add a command to this plug-in, right-click in the 
# script editor and choose Tools > Add Command.
# 
# Tip: To get help on a callback, highlight the callback name
# (for example, "Init", "Define", or "Execute") and press F1.
import win32com.client
from win32com.client import constants

null = None
false = 0
true = 1

xsi = Application
log = xsi.logmessage

def XSILoadPlugin( in_reg ):
	in_reg.Author = "andy"
	in_reg.Name = "CreateNullAtSelection"
	in_reg.Major = 1
	in_reg.Minor = 0

	in_reg.RegisterCommand("CreateNullAtSelection","CreateNullAtSelection")
	in_reg.RegisterMenu(constants.siMenuTbGetPrimitiveID,"CreateNullAtSelection_Menu",false,false)
	#RegistrationInsertionPoint - do not remove this line

	return true

def XSIUnloadPlugin( in_reg ):
	strPluginName = in_reg.Name
	Application.LogMessage(str(strPluginName) + str(" has been unloaded."),constants.siVerbose)
	return true

def CreateNullAtSelection_Init( in_ctxt ):
	oCmd = in_ctxt.Source
	oCmd.Description = ""
	oCmd.ReturnValue = true

	return true

def CreateNullAtSelection_Execute(  ):

	# create an aggregate vector #
	v_agg = XSIMath.CreateVector3()

	# get the selected point point #
	count = xsi.selection(0).SubComponent.ComponentCollection.Count
	
	# step through each vert and position #
	for vert in xsi.selection(0).SubComponent.ComponentCollection:
		# add in the vertex position #
		v_agg.AddInPlace(vert.Position)

	# get the average position #
	v_agg.ScaleInPlace(1.0/float(count))

	# add the global position of the selected geom #
	v_agg.AddInPlace(xsi.selection(0).SubComponent.Parent3DObject.Kinematics.Global.Transform.Translation)

	# create a null at the position #
	null = xsi.ActiveSceneRoot.AddNull()
	tfm = null.Kinematics.Global.Transform
	tfm.Translation = v_agg
	null.Kinematics.Global.Transform = tfm

	return true

def CreateNullAtSelection_Menu_Init( in_ctxt ):
	oMenu = in_ctxt.Source
	oMenu.AddCommandItem("Create Null At Selection","CreateNullAtSelection")
	return true

